[package]
name = "deeds"
version = "1.0.0"
authors = []

[addresses]
deeds = "_"

[dev-addresses]
deeds = "0xca7f4c4d7b89d5c91d7e8c5f3a2b1d9e4c6f8a1b2c3d4e5f6a7b8c9d0e1f2a3b"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-stdlib"

[dev-dependencies]